### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by justinmarkfarrugia** [Kinark/Materialize-stepper#1]
@Kinark First off, thanks for building this. I'm trying to demo what you've built but I'm getting the error cannot read property setDefaults of undefined(...) and thus the function isn't being initialized. Would you mind helping me resolve this issue? In the attached file, I only included index.html to test this out. Maybe it's a typo on your end, or possibly mine.
[Materialize-stepper.zip](https://github.com/Kinark/Materialize-stepper/files/520089/Materialize-stepper.zip)

**Comment by Kinark** [comment]
Oh, my bad. I forgot to include the jQueryValidation plugin into the install instructions.
Just included it in your index.html file (after materialize.min.js) and everything worked.

Here is the CDN of the plugin:
https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js

I've also updated README.md to fix it

Thank you and sorry!

Ps.: I recommend you to update to v1.2. There is some really idiot bugs fixed in recent version :D

**Comment by aronmoshe-m** [comment]
@Kinark I don't think this was ever added to the readme. If I pull down and create a PR, would you approve it?

**Comment by Kinark** [comment]
Yep, for sure, but since I ditched jquery I can't requal which lib I'm using now

**Comment by Kinark** [comment]
@aronmoshe-m ok so, I'm not using any lib anymore. I'm just leaving the validation up to the user.
