### ISSUE TITLE
window[feedback] is undefined

### ISSUE THREAD

**Issue by marleybobby** [Kinark/Materialize-stepper#10]
I took a look at your example at codepen. I tried to use the feedback function but somehow i always receive this message: 
**window[feedback] is undefined**

```
<button class="waves-effect waves-dark btn" id="create" data-feedback="cm_submit">Create</button>
 
 function cm_submit() {
         console.log("asdasd");
   }

```

Am I doing sth. totally wrong or is it a bug?

Greetings

**Comment by Kinark** [comment]
So, the only thing that could happen in this case would be the form being submited, since feedback function is only called on buttons with `type="submit"` or with the classes `.next-step` and `.previous-step`.

Could you post your entire code?

In any case, unless you're trying to achieve something different from the default stepper's functions, I recommend you to use one of the three "attributes" listed above in all of your buttons inside the stepper.

It shouldn't be happenning. I tested myself and works fine ;-;

**Comment by Kinark** [comment]
Since nothing new came up, I'm closing the issue for now.

**Comment by shiflonium** [comment]
I encountered the same problem. 

I have 2 steps.

The button on which I am trying to apply the feedback function is on the first step and supposed to lead to the second step. My stepper is wrapped with my own form tag (don't know if this matters)

This is my button:

`<button id="continue-signup" 
class="btn waves-effect waves-light black next-step" data-feedback="testFunc">Continue</button>`

My javascript function is

```
function testFunc(){
    console.log(111);
}
```

I ended up implementing this workflow manually by using on click event on the button, preventing default behavior and propagation to stop it from advancing to the next step and then, calling activateFeedback(). Then I ran my feedback function and after the function returns, I called nextStep().

Hope this helps anyone who encounters the same problem
