### ISSUE TITLE
export is needed

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [Kinark/Materialize-stepper#55]
Hi, I needed this at the last of dist/js/mstepper.js. I'm not sure but you needed export class in the source?

```
module.exports = MStepper;
```
I have not succeeded to update my app for 3.0.0 beta.

**Comment by Kinark** [comment]
I believe you're trying to use MStepper in a modularized environment (like using webpack or browserify) and attempting to `import` or `require` the plugin.

However, I'm only using babel and es6 to make the code better, cause the dist version is compiled into vanilla js, so it can be used with a `script` tag.

In order to use MStepper in a modularized environment, I recommend searching something like "importing global js lib webpack (or browserify, etc...)".

If webpack is the case, here's some useful links:
https://webpack.js.org/guides/shimming/
https://stackoverflow.com/questions/37656592/define-global-variable-with-webpack

The same problem occurs if you try to import jQuery, for example. 

I plan to make a modularized version (with module exports) of it soon, and even a react component, but for now, this is the way to go :(

If your problem wasn't solved, I'll be here :) 
Meanwhile, I'll leave this issue opened.

**Comment by jlipford** [comment]
@HIRANO-Satoshi did you ever get this module loading correctly? I am using webpack and exports-loader and it is still not loading correctly into my SPA application.

**Comment by jlipford** [comment]
Nevermind, just got it working. For anyone who wants to use this component in modularized environment (for me it was WebPack).
1. use exports-loader to export MStepper
2. reference it in your file (I am using typescript):
import MStepper from 'materialize-stepper/dist/js/mstepper.min';

**Comment by HIRANO-Satoshi** [comment]
@jlipford Happy to hear that. 

I'm happy with the following imports for MStepper **2** and webpack.

import 'materialize-stepper/materialize-stepper.min.css';
import 'materialize-stepper/materialize-stepper.min.js';

**Comment by cunneen** [comment]
This config worked for me:

1. 

```
npm install exports-loader --save-dev
npm install materialize-stepper --save
```

2. In my `webpack.config.js` :

```js
module.exports = {
  // ...
  module: {
    rules: [
      // ...
      {
        test: /materialize-stepper/,
        exclude: /\.css$/, // prevent our CSS file from being matched.
        use: 'exports-loader?MStepper', // adds module.exports = MStepper to the materialise-stepper main file
      },
    ]
  }
```

3. In my JS file that creates a new `MStepper`:
```js
import 'materialize-stepper/dist/css/mstepper.min.css';
import MStepper from 'materialize-stepper';
// ...
const stepperInstance = new MStepper(stepper, {...});
```

**Comment by cunneen** [comment]
This config worked for me:

1. 

```
npm install exports-loader --save-dev
npm install materialize-stepper --save
```

2. In my `webpack.config.js` :

```js
module.exports = {
  // ...
  module: {
    rules: [
      // ...
      {
        test: /materialize-stepper/,
        exclude: /\.css$/, // prevent our CSS file from being matched.
        use: 'exports-loader?MStepper', // adds 
      },
    ]
  }
```

3. In my JS file that creates a new `MStepper`:
```js
import 'materialize-stepper/dist/css/mstepper.min.css';
import MStepper from 'materialize-stepper';
// ...
const stepperInstance = new MStepper(stepper, {...});
```

**Comment by shamseen** [comment]
@cunneen Hi! I'm a bit new to this. Are you editing the config in node_modules > react-scripts > config ? I am getting an error: 

```
./node_modules/materialize-stepper/dist/js/mstepper.js
ValidationError: Invalid options object. Exports Loader has been initialized using an options object that does not match the API schema.
 - options misses the property 'exports'. Should be:
   non-empty string | object { name, syntax?, alias? } | [non-empty string | object { name, syntax?, alias? }, ...] (should not have fewer than 1 item)
```

**Comment by cunneen** [comment]
Hi @shamseen , my comment refers to webpack configuration (usually in the root folder, `webpack.config.js`). In my case I wasn't using react for this project, but I was using webpack. From your error message, it looks like the `exports-loader` isn't initialising properly; beyond that I'm not going to be able to help much I'm afraid.
